package org.dataone.cn.dao.exceptions;

public class DataAccessException extends Exception {

    public DataAccessException(Throwable cause) {
        super(cause);
    }
}
